import "./globals.css";
import Provider from "./components/Provider";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" suppressHydrationWarning={true}>

      <body>
        <Provider >

        {children}
        </Provider>
      </body>
    </html>
  );
}
